export { default as IconArrow } from './IconArrow.vue'
export { default as IconCheck } from './IconCheck.vue'
export { default as IconClose } from './IconClose.vue'
export { default as IconInfo } from './IconInfo.vue'
export { default as IconKebab } from './IconKebab.vue'
export { default as IconLink } from './IconLink.vue'
export { default as IconRefresh } from './IconRefresh.vue'
export { default as IconWarning } from './IconWarning.vue'
