// @vitest-environment node
/**
 * Functional end-to-end test of the Lieutenant tab pipeline.
 *
 * Tests the REAL function chain used by LieutenantsSelection.vue:
 *   1. Read cached SERP data for captain + root keywords
 *   2. mergeSerpResults() — dedup competitors & PAA
 *   3. Hn recurrence computation on merged data
 *   4. Prompt building for propose-lieutenants (real template + real data)
 *   5. Pipeline summary
 *
 * Uses CACHED SERP data directly (no DataForSEO API), so it's fast and deterministic.
 * Article: "Création de site web sur mesure à Toulouse..."
 * Captain: "creation site web entreprises Toulouse"
 */
import { describe, it, expect, vi, beforeAll } from 'vitest'

// --- Mock logger to avoid console noise ---
vi.mock('../../server/utils/logger', () => ({
  log: { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))

// --- Mock cache-helpers with synthetic SERP data ---
const SYNTHETIC_SERP_DATA: Record<string, any> = {
  'creation-site-web-entreprises-toulouse': {
    keyword: 'creation site web entreprises Toulouse',
    articleLevel: 'pilier',
    competitors: [
      { position: 1, title: 'Création site web Toulouse', url: 'https://a.com', domain: 'a.com', headings: [{ level: 1, text: 'Création de site web' }, { level: 2, text: 'Pourquoi choisir nous' }], textContent: 'creation site web toulouse' },
      { position: 2, title: 'Agence web Toulouse', url: 'https://b.com', domain: 'b.com', headings: [{ level: 1, text: 'Agence web' }, { level: 2, text: 'Nos services' }, { level: 2, text: 'Pourquoi choisir nous' }], textContent: 'agence web toulouse' },
      { position: 3, title: 'Développement web', url: 'https://c.com', domain: 'c.com', headings: [{ level: 1, text: 'Développement web' }, { level: 2, text: 'Nos services' }], textContent: 'developpement web' },
    ],
    paaQuestions: [
      { question: 'Comment créer un site web ?', answer: 'En faisant appel à une agence' },
      { question: 'Combien coûte un site web ?', answer: 'Entre 1000 et 10000 euros' },
    ],
    maxScraped: 3,
    cachedAt: new Date().toISOString(),
    fromCache: false,
  },
  'creation-site-web-entreprises': {
    keyword: 'creation site web entreprises',
    articleLevel: 'pilier',
    competitors: [
      { position: 1, title: 'Création site pour entreprises', url: 'https://d.com', domain: 'd.com', headings: [{ level: 1, text: 'Création site' }, { level: 2, text: 'Nos services' }], textContent: 'creation site entreprises' },
    ],
    paaQuestions: [{ question: 'Quel budget pour un site ?', answer: '1000 euros minimum' }],
    maxScraped: 1,
    cachedAt: new Date().toISOString(),
    fromCache: false,
  },
}

vi.mock('../../server/db/cache-helpers', () => ({
  slugify: (text: string) => text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
  getCached: vi.fn((_cacheType: string, key: string) => Promise.resolve(SYNTHETIC_SERP_DATA[key] ?? null)),
  setCached: vi.fn(),
}))

import { getCached, slugify } from '../../server/db/cache-helpers'
import { loadPrompt } from '../../server/utils/prompt-loader'
import type { SerpAnalysisResult, SerpCompetitor } from '../../shared/types/serp-analysis.types'
import type { PaaQuestion } from '../../shared/types/dataforseo.types'

// ---------------------------------------------------------------------------
// Constants — real article data
// ---------------------------------------------------------------------------
const CAPTAIN_KEYWORD = 'creation site web entreprises Toulouse'
const ARTICLE_LEVEL = 'pilier' as const

// Root keywords generated by extractRoots("creation site web entreprises Toulouse")
// 5 words → truncations at 4, 3, 2 words (all have ≥2 significant words)
const ROOT_KEYWORDS = [
  'creation site web entreprises',
  'creation site web',
  'creation site',
]

// ---------------------------------------------------------------------------
// mergeSerpResults — same logic as in LieutenantsSelection.vue
// ---------------------------------------------------------------------------
function mergeSerpResults(results: SerpAnalysisResult[]): SerpAnalysisResult {
  if (results.length === 1) return results[0]

  const base = results[0]
  const seenUrls = new Set<string>()
  const mergedCompetitors: SerpCompetitor[] = []
  const seenPaa = new Set<string>()
  const mergedPaa: PaaQuestion[] = []

  for (const r of results) {
    for (const c of r.competitors) {
      if (!seenUrls.has(c.url)) {
        seenUrls.add(c.url)
        mergedCompetitors.push(c)
      }
    }
    for (const p of r.paaQuestions) {
      const key = p.question.toLowerCase().trim()
      if (!seenPaa.has(key)) {
        seenPaa.add(key)
        mergedPaa.push(p)
      }
    }
  }

  return {
    ...base,
    competitors: mergedCompetitors,
    paaQuestions: mergedPaa,
    maxScraped: mergedCompetitors.length,
  }
}

// ---------------------------------------------------------------------------
// hnRecurrence — same logic as in LieutenantsSelection.vue
// ---------------------------------------------------------------------------
interface HnRecurrenceItem {
  level: number
  text: string
  count: number
  total: number
  percent: number
}

function computeHnRecurrence(competitors: SerpCompetitor[]): HnRecurrenceItem[] {
  const comps = competitors.filter(c => !c.fetchError)
  const total = comps.length
  if (total === 0) return []

  const freqMap = new Map<string, { level: number; text: string; count: number }>()

  for (const comp of comps) {
    const seen = new Set<string>()
    for (const h of comp.headings) {
      const key = `${h.level}:${h.text.toLowerCase().trim()}`
      if (seen.has(key)) continue
      seen.add(key)

      const existing = freqMap.get(key)
      if (existing) {
        existing.count++
      } else {
        freqMap.set(key, { level: h.level, text: h.text, count: 1 })
      }
    }
  }

  return Array.from(freqMap.values())
    .map(item => ({ ...item, total, percent: Math.round(item.count / total * 100) }))
    .sort((a, b) => b.percent - a.percent || a.level - b.level)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
describe('Lieutenant tab — functional E2E pipeline', () => {
  // Shared state across test steps
  const serpResults: SerpAnalysisResult[] = []
  let mergedResult: SerpAnalysisResult
  let hnRecurrence: HnRecurrenceItem[]

  // -----------------------------------------------------------------------
  // Step 1: Load cached SERP data for captain + root keywords
  // -----------------------------------------------------------------------
  describe('Step 1 — Load cached SERP data (captain + roots)', () => {
    beforeAll(async () => {
      const allKeywords = [CAPTAIN_KEYWORD, ...ROOT_KEYWORDS]
      for (const kw of allKeywords) {
        const cacheKey = slugify(kw)
        const cached = await getCached<SerpAnalysisResult>('serp', cacheKey)
        if (cached) {
          serpResults.push({ ...cached, fromCache: true })
        }
      }
    })

    it('should load cached SERP for captain keyword', () => {
      expect(serpResults.length).toBeGreaterThanOrEqual(1)
      expect(serpResults[0].keyword).toBe(CAPTAIN_KEYWORD)
      expect(serpResults[0].competitors.length).toBeGreaterThan(0)
    })

    it('should load at least the captain keyword cache', () => {
      // Root keywords may or may not be cached — captain always is
      // eslint-disable-next-line no-console
      console.log(`[E2E] Cached keywords loaded: ${serpResults.length}/${[CAPTAIN_KEYWORD, ...ROOT_KEYWORDS].length}`)
      for (const r of serpResults) {
        console.log(`  - "${r.keyword}": ${r.competitors.length} competitors, ${r.paaQuestions.length} PAA`)
      }
    })

    it('should have captain keyword with competitors', () => {
      const captain = serpResults.find(r => r.keyword === CAPTAIN_KEYWORD)
      expect(captain).toBeDefined()
      expect(captain!.competitors.length).toBeGreaterThan(0)
    })
  })

  // -----------------------------------------------------------------------
  // Step 2: Merge SERP results
  // -----------------------------------------------------------------------
  describe('Step 2 — Merge SERP results (deduplication)', () => {
    beforeAll(() => {
      mergedResult = mergeSerpResults(serpResults)
    })

    it('should produce a merged result', () => {
      expect(mergedResult).toBeDefined()
      expect(mergedResult.competitors).toBeDefined()
      expect(mergedResult.paaQuestions).toBeDefined()
    })

    it('should have ≥ captain-only competitors after merge', () => {
      const captainOnly = serpResults[0].competitors.length
      expect(mergedResult.competitors.length).toBeGreaterThanOrEqual(captainOnly)
    })

    it('should deduplicate competitors by URL', () => {
      const urls = mergedResult.competitors.map(c => c.url)
      const uniqueUrls = new Set(urls)
      expect(urls.length).toBe(uniqueUrls.size)
    })

    it('should deduplicate PAA by question text', () => {
      const questions = mergedResult.paaQuestions.map(p => p.question.toLowerCase().trim())
      const uniqueQuestions = new Set(questions)
      expect(questions.length).toBe(uniqueQuestions.size)
    })

    it('should have non-empty competitor data', () => {
      const validComps = mergedResult.competitors.filter(c => !c.fetchError)
      expect(validComps.length).toBeGreaterThan(0)

      // At least some competitors should have headings
      const withHeadings = validComps.filter(c => c.headings.length > 0)
      expect(withHeadings.length).toBeGreaterThan(0)
    })

    it('should log merge enrichment', () => {
      const captainOnly = serpResults[0].competitors.length
      const merged = mergedResult.competitors.length
      const enrichment = merged - captainOnly
      // eslint-disable-next-line no-console
      console.log(`[E2E] Captain-only: ${captainOnly} competitors → Merged: ${merged} competitors (+${enrichment} from roots)`)
      console.log(`[E2E] PAA: ${mergedResult.paaQuestions.length} unique questions`)
      expect(merged).toBeGreaterThanOrEqual(captainOnly)
    })
  })

  // -----------------------------------------------------------------------
  // Step 3: Hn Recurrence computation
  // -----------------------------------------------------------------------
  describe('Step 3 — Hn recurrence from merged competitors', () => {
    beforeAll(() => {
      hnRecurrence = computeHnRecurrence(mergedResult.competitors)
    })

    it('should compute heading recurrence items', () => {
      expect(hnRecurrence.length).toBeGreaterThan(0)
    })

    it('should have items with correct structure', () => {
      for (const item of hnRecurrence.slice(0, 5)) {
        expect(item.level).toBeGreaterThanOrEqual(1)
        expect(item.level).toBeLessThanOrEqual(6)
        expect(typeof item.text).toBe('string')
        expect(item.count).toBeGreaterThanOrEqual(1)
        expect(item.total).toBeGreaterThan(0)
        expect(item.percent).toBeGreaterThanOrEqual(0)
        expect(item.percent).toBeLessThanOrEqual(100)
      }
    })

    it('should report ≥10% recurrence threshold headings', () => {
      const above10 = hnRecurrence.filter(h => h.percent >= 10)
      // eslint-disable-next-line no-console
      console.log(`[E2E] Headings ≥10%: ${above10.length} (total unique headings: ${hnRecurrence.length})`)
      if (above10.length > 0) {
        for (const h of above10.slice(0, 10)) {
          console.log(`  - H${h.level}: "${h.text}" (${h.count}/${h.total} = ${h.percent}%)`)
        }
      }
    })
  })

  // -----------------------------------------------------------------------
  // Step 4: Prompt building for propose-lieutenants
  // -----------------------------------------------------------------------
  describe('Step 4 — Prompt building with real SERP data', () => {
    let prompt: string

    beforeAll(async () => {
      const filteredHn = hnRecurrence
        .filter(h => h.percent >= 10)
        .map(h => ({ level: h.level, text: h.text, count: h.count, percent: h.percent }))

      const competitors = mergedResult.competitors
        .filter(c => !c.fetchError)
        .map(c => ({ domain: c.domain, title: c.title, position: c.position }))

      const paaFormatted = mergedResult.paaQuestions.length > 0
        ? mergedResult.paaQuestions.map(q => `- ${q.question}${q.answer ? ` → ${q.answer}` : ''}`).join('\n')
        : 'Aucune PAA disponible pour cette requête.'

      const hnFormatted = filteredHn.length > 0
        ? filteredHn.map(h => `H${h.level}: "${h.text}" (${h.count}x, ${h.percent}%)`).join('\n')
        : 'Aucun heading avec récurrence significative parmi les concurrents.'

      const competitorsFormatted = competitors.length > 0
        ? competitors.map(c => `#${c.position} ${c.domain} — "${c.title}"`).join('\n')
        : 'Aucune donnée concurrents disponible.'

      prompt = await loadPrompt('propose-lieutenants', {
        keyword: CAPTAIN_KEYWORD,
        level: ARTICLE_LEVEL,
        paa_questions: paaFormatted,
        hn_recurrence: hnFormatted,
        serp_competitors: competitorsFormatted,
        word_groups: 'Aucun groupe disponible',
        root_keywords: ROOT_KEYWORDS.join(', '),
        existing_lieutenants: 'Aucun (premier article du cocon)',
      })
    })

    it('should build a non-empty prompt', () => {
      expect(prompt.length).toBeGreaterThan(500)
    })

    it('should contain the captain keyword', () => {
      expect(prompt).toContain(CAPTAIN_KEYWORD)
    })

    it('should contain the article level', () => {
      expect(prompt).toContain(ARTICLE_LEVEL)
    })

    it('should have all placeholders replaced', () => {
      expect(prompt).not.toContain('{{serp_competitors}}')
      expect(prompt).not.toContain('{{paa_questions}}')
      expect(prompt).not.toContain('{{hn_recurrence}}')
      expect(prompt).not.toContain('{{keyword}}')
      expect(prompt).not.toContain('{{level}}')
      expect(prompt).not.toContain('{{word_groups}}')
      expect(prompt).not.toContain('{{root_keywords}}')
      expect(prompt).not.toContain('{{existing_lieutenants}}')
    })

    it('should contain real competitor data', () => {
      const validComps = mergedResult.competitors.filter(c => !c.fetchError)
      if (validComps.length > 0) {
        expect(prompt).toContain(validComps[0].domain)
      }
    })

    it('should contain root keywords', () => {
      for (const rk of ROOT_KEYWORDS) {
        expect(prompt).toContain(rk)
      }
    })

    it('should report data quality summary', () => {
      // eslint-disable-next-line no-console
      console.log(`[E2E] Prompt length: ${prompt.length} chars`)
      console.log(`[E2E] Has PAA data: ${mergedResult.paaQuestions.length > 0}`)
      console.log(`[E2E] Has Hn data: ${hnRecurrence.filter(h => h.percent >= 10).length > 0}`)
      console.log(`[E2E] Competitors in prompt: ${mergedResult.competitors.filter(c => !c.fetchError).length}`)
    })
  })

  // -----------------------------------------------------------------------
  // Pipeline summary
  // -----------------------------------------------------------------------
  describe('Pipeline summary', () => {
    it('should print end-to-end pipeline metrics', () => {
      const captainComps = serpResults[0]?.competitors.length ?? 0
      const mergedComps = mergedResult?.competitors.length ?? 0
      const captainPaa = serpResults[0]?.paaQuestions.length ?? 0
      const mergedPaa = mergedResult?.paaQuestions.length ?? 0
      const hnTotal = hnRecurrence?.length ?? 0
      const hnAbove10 = hnRecurrence?.filter(h => h.percent >= 10).length ?? 0

      // eslint-disable-next-line no-console
      console.log('\n=== LIEUTENANT TAB E2E PIPELINE ===')
      console.log(`Captain keyword: "${CAPTAIN_KEYWORD}"`)
      console.log(`Article level: ${ARTICLE_LEVEL}`)
      console.log(`Keywords analyzed: ${serpResults.length} (from cache)`)
      console.log(`Competitors: ${captainComps} (captain only) → ${mergedComps} (merged, +${mergedComps - captainComps})`)
      console.log(`PAA questions: ${captainPaa} (captain only) → ${mergedPaa} (merged)`)
      console.log(`Hn headings: ${hnTotal} total, ${hnAbove10} with ≥10% recurrence`)
      console.log('===================================\n')
    })
  })
})
