/** Strategy data for a single article — 6-step Brain-First workflow */

import type { ArticleType } from './article.types.js'

export interface SubQuestion {
  id: string
  question: string
  description: string
  input: string
  suggestion: string | null
  validated: string
}

export interface StrategyStepData {
  input: string
  suggestion: string | null
  validated: string
  subQuestions?: SubQuestion[]
}

export interface AiguillageData {
  suggestedType: ArticleType | null
  suggestedParent: string | null
  suggestedChildren: string[]
  validated: boolean
}

export interface CtaData {
  type: 'service' | 'formulaire' | 'guide' | 'autre'
  target: string
  suggestion: string | null
}

export interface ArticleStrategy {
  slug: string
  cible: StrategyStepData
  douleur: StrategyStepData
  aiguillage: AiguillageData
  angle: StrategyStepData
  promesse: StrategyStepData
  cta: CtaData
  completedSteps: number
  updatedAt: string
}

/** Contextual data injected into AI prompts for richer suggestions */
export interface ThemeContext {
  themeName?: string
  themeDescription?: string
  siloDescription?: string
  cocoonArticles?: string[]
  cocoonStrategy?: Record<string, string>
  themeConfig?: {
    // Votre entreprise
    mainPromise?: string
    differentiators?: string[]
    services?: string[]
    mainCTA?: string
    location?: string
    // Votre client type
    targetAudience?: string
    sector?: string
    companySize?: string
    budget?: string
    digitalMaturity?: string
    painPoints?: string[]
    // Votre communication
    toneStyle?: string
    vocabulary?: string[]
  }
}

/** Payload for POST /api/strategy/:slug/deepen */
export interface StrategyDeepenRequest {
  step: 'cible' | 'douleur' | 'angle' | 'promesse'
  mainQuestion: string
  mainAnswer: string
  existingSubQuestions: Array<{ question: string; answer: string }>
  context: {
    articleTitle?: string
    cocoonName: string
    siloName: string
    previousAnswers?: Record<string, string>
    themeContext?: ThemeContext
  }
}

export interface StrategyDeepenResponse {
  question: string
  description: string
}

/** Payload for POST /api/strategy/:slug/enrich */
export interface StrategyEnrichRequest {
  step: 'cible' | 'douleur' | 'angle' | 'promesse'
  existingValidated: string
  subQuestion: string
  subAnswer: string
  context: {
    articleTitle?: string
    cocoonName: string
    siloName: string
    previousAnswers?: Record<string, string>
    themeContext?: ThemeContext
  }
}

export interface StrategyEnrichResponse {
  enriched: string
}

/** Payload for POST /api/strategy/:slug/consolidate */
export interface StrategyConsolidateRequest {
  step: 'cible' | 'douleur' | 'angle' | 'promesse'
  mainAnswer: string
  subAnswers: Array<{ question: string; answer: string }>
  context: {
    articleTitle?: string
    cocoonName: string
    siloName: string
    previousAnswers?: Record<string, string>
    themeContext?: ThemeContext
  }
}

export interface StrategyConsolidateResponse {
  consolidated: string
}

/** Payload for POST /api/strategy/:slug/suggest */
export interface StrategySuggestRequest {
  step: 'cible' | 'douleur' | 'aiguillage' | 'angle' | 'promesse' | 'cta'
  currentInput: string
  /** When present, triggers a merge: Claude fuses currentInput + mergeWith into one coherent text */
  mergeWith?: string
  /** Already-validated text for this step — merge should enrich it, not replace it */
  existingValidated?: string
  context: {
    articleTitle: string
    cocoonName: string
    siloName: string
    existingArticles?: string[]
    previousAnswers?: Record<string, string>
    themeContext?: ThemeContext
  }
}

export interface StrategySuggestResponse {
  suggestion: string
}

/** Proposed article generated by cocoon-level brainstorm */
export interface ProposedArticle {
  title: string
  suggestedTitles: string[]
  type: ArticleType
  parentTitle: string | null
  rationale: string
  painPoint: string
  suggestedKeyword: string
  suggestedKeywords: string[]
  suggestedSlug: string
  suggestedSlugs: string[]
  validatedSearchQuery: string | null
  keywordValidated: boolean
  searchQueryValidated: boolean
  titleValidated: boolean
  accepted: boolean
  createdInDb: boolean
}

/** Strategy data for a cocoon — 6-step brainstorm workflow */
export interface CocoonStrategy {
  cocoonSlug: string
  cible: StrategyStepData
  douleur: StrategyStepData
  angle: StrategyStepData
  promesse: StrategyStepData
  cta: StrategyStepData
  proposedArticles: ProposedArticle[]
  completedSteps: number // 0-6
  updatedAt: string
}

/** Lightweight strategic context for Moteur display */
export interface StrategyContextData {
  cocoonName: string
  siloName: string
  cible: string | null
  douleur: string | null
  angle: string | null
  promesse: string | null
  cta: string | null
}

/** Payload for POST /api/strategy/cocoon/:slug/suggest */
export interface CocoonSuggestRequest {
  step: 'cible' | 'douleur' | 'angle' | 'promesse' | 'cta' | 'articles' | 'articles-structure' | 'articles-paa-queries' | 'articles-spe' | 'add-article'
  currentInput: string
  /** When present, triggers a merge: Claude fuses currentInput + mergeWith into one coherent text */
  mergeWith?: string
  /** Already-validated text for this step — merge should enrich it, not replace it */
  existingValidated?: string
  context: {
    cocoonName: string
    siloName: string
    previousAnswers?: Record<string, string>
    existingArticles?: string[]
    themeContext?: ThemeContext
    /** PAA questions grouped by Inter title — used by articles-spe step */
    paaContext?: Record<string, Array<{ question: string; answer: string | null }>>
  }
}
