// @vitest-environment node
import { describe, it, expect, vi, beforeEach } from 'vitest'
import type { Cocoon, Keyword, ArticleKeywords } from '../../../shared/types/index'

// Mock data.service before importing the service
vi.mock('../../../server/services/infra/data.service', () => ({
  getCocoons: vi.fn(),
  getKeywordsByCocoon: vi.fn(),
  saveArticleKeywords: vi.fn(),
  getArticleKeywordsByCocoon: vi.fn(),
}))

// Mock logger
vi.mock('../../../server/utils/logger', () => ({
  log: { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}))

import { getCocoons, getKeywordsByCocoon, saveArticleKeywords, getArticleKeywordsByCocoon } from '../../../server/services/infra/data.service'
import { previewMigration, applyMigration } from '../../../server/services/keyword/keyword-assignment.service'

const mockGetCocoons = vi.mocked(getCocoons)
const mockGetKeywordsByCocoon = vi.mocked(getKeywordsByCocoon)
const mockSaveArticleKeywords = vi.mocked(saveArticleKeywords)
const mockGetArticleKeywordsByCocoon = vi.mocked(getArticleKeywordsByCocoon)

const MOCK_COCOON: Cocoon = {
  id: 0,
  name: 'Design Web',
  siloName: 'Web',
  articles: [
    { id: 1, title: 'Guide du design web', type: 'Pilier', slug: 'guide-design-web', topic: null, status: 'à rédiger' },
    { id: 2, title: 'Couleurs en web design', type: 'Intermédiaire', slug: 'couleurs-web-design', topic: null, status: 'à rédiger' },
    { id: 3, title: 'Typographie web', type: 'Intermédiaire', slug: 'typographie-web', topic: null, status: 'à rédiger' },
    { id: 4, title: 'Micro-interactions CSS', type: 'Spécialisé', slug: 'micro-interactions-css', topic: null, status: 'à rédiger' },
    { id: 5, title: 'Dark mode design', type: 'Spécialisé', slug: 'dark-mode-design', topic: null, status: 'à rédiger' },
  ],
  stats: { totalArticles: 5, byType: { pilier: 1, intermediaire: 2, specialise: 2 }, byStatus: { aRediger: 5, brouillon: 0, publie: 0 }, completionPercent: 0 },
}

const MOCK_KEYWORDS: Keyword[] = [
  { keyword: 'design web', cocoonName: 'Design Web', type: 'Pilier' },
  { keyword: 'couleurs web', cocoonName: 'Design Web', type: 'Intermédiaire' },
  { keyword: 'palette de couleurs', cocoonName: 'Design Web', type: 'Intermédiaire' },
  { keyword: 'typographie responsive', cocoonName: 'Design Web', type: 'Intermédiaire' },
  { keyword: 'police de caractères web', cocoonName: 'Design Web', type: 'Intermédiaire' },
  { keyword: 'animations CSS micro-interactions', cocoonName: 'Design Web', type: 'Spécialisé' },
  { keyword: 'dark mode CSS variables', cocoonName: 'Design Web', type: 'Spécialisé' },
  { keyword: 'design sombre accessibilité', cocoonName: 'Design Web', type: 'Spécialisé' },
  { keyword: 'transitions hover CSS', cocoonName: 'Design Web', type: 'Spécialisé' },
]

beforeEach(() => {
  mockGetCocoons.mockReset()
  mockGetKeywordsByCocoon.mockReset()
  mockSaveArticleKeywords.mockReset()
  mockGetArticleKeywordsByCocoon.mockReset()
})

describe('keyword-assignment.service — previewMigration', () => {
  it('returns assignments with correct distribution across article types', async () => {
    mockGetCocoons.mockResolvedValue([MOCK_COCOON])
    mockGetKeywordsByCocoon.mockResolvedValue(MOCK_KEYWORDS)
    mockGetArticleKeywordsByCocoon.mockResolvedValue([])

    const preview = await previewMigration('Design Web')

    expect(preview.cocoonName).toBe('Design Web')
    expect(preview.assignments).toHaveLength(5)

    // Pilier article gets Pilier keyword as capitaine
    const pilierAssignment = preview.assignments.find(a => a.articleId === 1)
    expect(pilierAssignment).toBeDefined()
    expect(pilierAssignment!.capitaine).toBe('design web')
    expect(pilierAssignment!.articleType).toBe('Pilier')

    // Intermédiaire articles get Moyenne traine keywords
    const interAssignments = preview.assignments.filter(a => a.articleType === 'Intermédiaire')
    expect(interAssignments).toHaveLength(2)
    // First intermédiaire should get first share of moyenne keywords
    expect(interAssignments[0]!.capitaine).toBeTruthy()
    // Second intermédiaire should get second share
    expect(interAssignments[1]!.capitaine).toBeTruthy()

    // Spécialisé articles get Longue traine keywords
    const specAssignments = preview.assignments.filter(a => a.articleType === 'Spécialisé')
    expect(specAssignments).toHaveLength(2)
    expect(specAssignments[0]!.capitaine).toBeTruthy()
    expect(specAssignments[1]!.capitaine).toBeTruthy()

    // All lexique fields should be empty (not generated by migration)
    for (const a of preview.assignments) {
      expect(a.lexique).toEqual([])
    }
  })

  it('warns about duplicate capitaines', async () => {
    // Create keywords with duplicates: two Pilier articles get the same keyword as capitaine
    const duplicateKeywords: Keyword[] = [
      { keyword: 'design web', cocoonName: 'Design Web', type: 'Pilier' },
      { keyword: 'design web', cocoonName: 'Design Web', type: 'Pilier' },
    ]
    const cocoonWithTwoPiliers: Cocoon = {
      ...MOCK_COCOON,
      articles: [
        { id: 10, title: 'Article A', type: 'Pilier', slug: 'article-a', topic: null, status: 'à rédiger' },
        { id: 11, title: 'Article B', type: 'Pilier', slug: 'article-b', topic: null, status: 'à rédiger' },
      ],
      stats: { totalArticles: 2, byType: { pilier: 2, intermediaire: 0, specialise: 0 }, byStatus: { aRediger: 2, brouillon: 0, publie: 0 }, completionPercent: 0 },
    }

    mockGetCocoons.mockResolvedValue([cocoonWithTwoPiliers])
    mockGetKeywordsByCocoon.mockResolvedValue(duplicateKeywords)
    mockGetArticleKeywordsByCocoon.mockResolvedValue([])

    const preview = await previewMigration('Design Web')

    expect(preview.warnings.some(w => w.includes('dupliqué'))).toBe(true)
  })

  it('warns about existing assignments', async () => {
    mockGetCocoons.mockResolvedValue([MOCK_COCOON])
    mockGetKeywordsByCocoon.mockResolvedValue(MOCK_KEYWORDS)
    mockGetArticleKeywordsByCocoon.mockResolvedValue([
      { articleId: 1, capitaine: 'old keyword', lieutenants: [], lexique: [] },
    ])

    const preview = await previewMigration('Design Web')

    expect(preview.warnings.some(w => w.includes('id=1') && w.includes('déjà'))).toBe(true)
  })

  it('throws for missing cocoon', async () => {
    mockGetCocoons.mockResolvedValue([MOCK_COCOON])

    await expect(previewMigration('Nonexistent Cocoon')).rejects.toThrow('Cocoon not found: Nonexistent Cocoon')
  })

  it('handles cocoon with no keywords gracefully', async () => {
    mockGetCocoons.mockResolvedValue([MOCK_COCOON])
    mockGetKeywordsByCocoon.mockResolvedValue(null)
    mockGetArticleKeywordsByCocoon.mockResolvedValue([])

    const preview = await previewMigration('Design Web')

    // Assignments should exist for articles but with empty capitaines
    expect(preview.assignments).toHaveLength(5)
    for (const a of preview.assignments) {
      expect(a.capitaine).toBe('')
    }
  })
})

describe('keyword-assignment.service — applyMigration', () => {
  it('saves all assignments via saveArticleKeywords', async () => {
    mockSaveArticleKeywords.mockImplementation(async (id, data) => ({
      articleId: id,
      ...data,
    }))

    const assignments = [
      { articleId: 10, articleTitle: 'A', articleType: 'Pilier', capitaine: 'kw1', lieutenants: ['kw2'], lexique: [] },
      { articleId: 11, articleTitle: 'B', articleType: 'Intermédiaire', capitaine: 'kw3', lieutenants: [], lexique: [] },
    ]

    const results = await applyMigration(assignments)

    expect(mockSaveArticleKeywords).toHaveBeenCalledTimes(2)
    expect(mockSaveArticleKeywords).toHaveBeenCalledWith(10, {
      capitaine: 'kw1',
      lieutenants: ['kw2'],
      lexique: [],
    })
    expect(mockSaveArticleKeywords).toHaveBeenCalledWith(11, {
      capitaine: 'kw3',
      lieutenants: [],
      lexique: [],
    })
    expect(results).toHaveLength(2)
    expect(results[0]!.articleId).toBe(10)
    expect(results[1]!.articleId).toBe(11)
  })
})
